init-year: add year submodule to super
Signed-off-by: Steffen Prohaska <prohaska@zib.de>

diff --git a/lib/call/init-year b/lib/call/init-year
--- a/lib/call/init-year
+++ b/lib/call/init-year
@@ -2,8 +2,6 @@
 # vim: sw=4
 set -o errexit -o nounset -o pipefail -o noglob
 
-export LC_ALL=C
-
 project="$1"
 year="$2"
 
@@ -27,6 +25,22 @@ fi
     touch .gitignore .gitmodules
     git add .gitignore .gitmodules
     git commit -m 'init'
+    cd ..
+
+    # Commit parent dir if it contains a Git repo.
+    if ! [ "$(git rev-parse --is-inside-work-tree 2>/dev/null)" = "true" ]; then
+        echo "    SKIP commit super: not a git working copy"
+    elif !  [ -f "$(git rev-parse --show-toplevel)/.gitmodules" ]; then
+        echo "    SKIP commit super: missing .gitmodules"
+    elif ! [ -w "$(git rev-parse --git-dir)" ]; then
+        echo "    SKIP commit super: cannot write to Git dir."
+    else
+        echo "    COMMIT super"
+        # Avoid permission denied if file owned by a different user.
+        rm -f '.git/COMMIT_EDITMSG' || true
+        git submodule add -- "./${year}" "${year}"
+        git commit -m "${year}: init"
+    fi
 ) 10<"$(stdlockdir)"
 
-exit ${cfg_exit_ok}
+exitok
